/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package clases;

import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.plaf.basic.BasicMenuBarUI;
import javax.swing.plaf.metal.MetalLookAndFeel;

/**
 *
 * @author shand
 */
public class AdminNegocio extends javax.swing.JFrame {

    /**
     * Creates new form AdminNegocio
     */
    String usuario="",id="";
    public AdminNegocio() {
        initComponents();
        menuBar.setUI(new BasicMenuBarUI(){});
        menuBar.setBackground(Color.decode("#BDF2E0"));
        this.setLocationRelativeTo(null);
        System.out.println(usuario);
        System.out.println(id);

    }
    
    public void setID(String ID){
        id=ID;
    }
    static void loadLookAndFeel() {
    try {
        UIManager.put("Menu.background", Color.decode("#BDF2E0"));
        UIManager.put("Menu.foreground", new Color(27, 100, 20));
        
        UIManager.put("Menu.selectionBackground", Color.decode("#90F2E0"));
        UIManager.put("Menu.selectionForeground", Color.BLACK);
        
        UIManager.put("MenuItem.background", Color.decode("#BDF2E0"));
        UIManager.put("MenuItem.selectionBackground", Color.decode("#95FF95"));
        UIManager.put("MenuItem.selectionForeground", Color.BLACK);
        
        UIManager.setLookAndFeel(new MetalLookAndFeel());
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        Inventario = new javax.swing.JMenu();
        Ingresarpro = new javax.swing.JMenuItem();
        Eliminarprod = new javax.swing.JMenuItem();
        Editarprod = new javax.swing.JMenuItem();
        MostrarProduct = new javax.swing.JMenuItem();
        Ventas = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Proveedores = new javax.swing.JMenu();
        Ingresarprov = new javax.swing.JMenuItem();
        EliminarProv = new javax.swing.JMenuItem();
        Editarprov = new javax.swing.JMenuItem();
        MostrarProv = new javax.swing.JMenuItem();
        Operaciones = new javax.swing.JMenu();
        CorteCaja = new javax.swing.JMenuItem();
        Registrovent = new javax.swing.JMenu();
        Editarvent = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        impTicket = new javax.swing.JMenuItem();
        Configuracion = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        ConfigUsuario = new javax.swing.JMenuItem();
        ConfigUsuario1 = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));
        desktopPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 310, 310));

        desktopPane.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 350));

        Inventario.setForeground(new java.awt.Color(102, 102, 102));
        Inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cajas.png"))); // NOI18N
        Inventario.setMnemonic('h');
        Inventario.setText("Inventario");
        Inventario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        Ingresarpro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/almacen-alternativo.png"))); // NOI18N
        Ingresarpro.setText("Ingresar productos");
        Ingresarpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarproActionPerformed(evt);
            }
        });
        Inventario.add(Ingresarpro);

        Eliminarprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar-producto.png"))); // NOI18N
        Eliminarprod.setText("Eliminar productos");
        Eliminarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarprodActionPerformed(evt);
            }
        });
        Inventario.add(Eliminarprod);

        Editarprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        Editarprod.setText("Editar productos");
        Editarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarprodActionPerformed(evt);
            }
        });
        Inventario.add(Editarprod);

        MostrarProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/almacen-alternativo.png"))); // NOI18N
        MostrarProduct.setText("Mostrar productos");
        MostrarProduct.setToolTipText("");
        MostrarProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarProductActionPerformed(evt);
            }
        });
        Inventario.add(MostrarProduct);

        menuBar.add(Inventario);

        Ventas.setForeground(new java.awt.Color(102, 102, 102));
        Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dolar.png"))); // NOI18N
        Ventas.setText("Ventas");
        Ventas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrito-de-compra-anadir.png"))); // NOI18N
        jMenu1.setText("Realizar venta");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boleto.png"))); // NOI18N
        jMenuItem1.setText("Imprimir ticker");
        jMenu1.add(jMenuItem1);

        Ventas.add(jMenu1);

        menuBar.add(Ventas);

        Proveedores.setForeground(new java.awt.Color(102, 102, 102));
        Proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lado-del-camion.png"))); // NOI18N
        Proveedores.setMnemonic('e');
        Proveedores.setText("Proveedores");
        Proveedores.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        Ingresarprov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lapiz.png"))); // NOI18N
        Ingresarprov.setMnemonic('y');
        Ingresarprov.setText("Ingresar proveedor");
        Ingresarprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarprovActionPerformed(evt);
            }
        });
        Proveedores.add(Ingresarprov);

        EliminarProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Busqueda.png"))); // NOI18N
        EliminarProv.setMnemonic('p');
        EliminarProv.setText("Eliminar proveedor");
        EliminarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProvActionPerformed(evt);
            }
        });
        Proveedores.add(EliminarProv);

        Editarprov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        Editarprov.setText("Editar proveedor");
        Editarprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarprovActionPerformed(evt);
            }
        });
        Proveedores.add(Editarprov);

        MostrarProv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lado-del-camion.png"))); // NOI18N
        MostrarProv.setText("Mostrar proveedor");
        MostrarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarProvActionPerformed(evt);
            }
        });
        Proveedores.add(MostrarProv);

        menuBar.add(Proveedores);

        Operaciones.setForeground(new java.awt.Color(102, 102, 102));
        Operaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios-alt.png"))); // NOI18N
        Operaciones.setMnemonic('f');
        Operaciones.setText("Operaciones");
        Operaciones.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        CorteCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lapiz.png"))); // NOI18N
        CorteCaja.setMnemonic('s');
        CorteCaja.setText("Corte de caja");
        CorteCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorteCajaActionPerformed(evt);
            }
        });
        Operaciones.add(CorteCaja);

        Registrovent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mano.png"))); // NOI18N
        Registrovent.setText("Ventas registradas");

        Editarvent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        Editarvent.setText("Editar ventas");
        Registrovent.add(Editarvent);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar (1).png"))); // NOI18N
        jMenuItem4.setText("Eliminar venta");
        Registrovent.add(jMenuItem4);

        impTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boleto.png"))); // NOI18N
        impTicket.setText("Imprimir ticket");
        Registrovent.add(impTicket);

        Operaciones.add(Registrovent);

        menuBar.add(Operaciones);

        Configuracion.setForeground(new java.awt.Color(102, 102, 102));
        Configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/retrato.png"))); // NOI18N
        Configuracion.setText("Usuarios");
        Configuracion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/anadir.png"))); // NOI18N
        jMenuItem3.setText("Agregar usuario");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Configuracion.add(jMenuItem3);

        ConfigUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ajustes.png"))); // NOI18N
        ConfigUsuario.setText("Editar Usuario");
        ConfigUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfigUsuarioActionPerformed(evt);
            }
        });
        Configuracion.add(ConfigUsuario);

        ConfigUsuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        ConfigUsuario1.setText("Eliminar Usuario");
        ConfigUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUusario(evt);
            }
        });
        Configuracion.add(ConfigUsuario1);

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        Salir.setText("Cerrar sesión");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Configuracion.add(Salir);

        menuBar.add(Configuracion);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        int op=JOptionPane.showConfirmDialog(null, "¿Realmente desea salir?", "Confirmar salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (op==0){
        Login obj=new Login();
        obj.setVisible(true);
        this.dispose();
        }
        
    }//GEN-LAST:event_SalirActionPerformed

    private void ConfigUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigUsuarioActionPerformed
        // TODO add your handling code here:
        Usersettings obj= new Usersettings();
        obj.setVisible(true);
        obj.setuser(usuario);      
    }//GEN-LAST:event_ConfigUsuarioActionPerformed
    public void setConfiguracion(String user){  
        usuario=user;
        
    }
    private void CorteCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorteCajaActionPerformed
        // TODO add your handling code here:
        ClientList obj= new ClientList();
        obj.setVisible(true);
    }//GEN-LAST:event_CorteCajaActionPerformed

    private void EliminarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProvActionPerformed
        // TODO add your handling code here:
        ProvSearch obj= new ProvSearch();
        obj.setVisible(true);
    }//GEN-LAST:event_EliminarProvActionPerformed

    private void IngresarprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarprovActionPerformed
        // TODO add your handling code here:
        ProvList obj= new ProvList();
        obj.setVisible(true);
    }//GEN-LAST:event_IngresarprovActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    Register obj = new Register();    
    obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void EliminarUusario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUusario
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarUusario

    private void IngresarproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarproActionPerformed
        // TODO add your handling code here:
        ProductList obj= new ProductList();
        obj.setVisible(true);
    }//GEN-LAST:event_IngresarproActionPerformed

    private void EliminarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarprodActionPerformed
       Eliminar obj= new Eliminar();
        obj.setVisible(true);
    }//GEN-LAST:event_EliminarprodActionPerformed

    private void EditarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarprodActionPerformed
        Update obj= new Update();
        obj.setVisible(true);
    }//GEN-LAST:event_EditarprodActionPerformed

    private void MostrarProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarProductActionPerformed
        // TODO add your handling code here:
        MostrarProduct obj= new MostrarProduct();
        obj.setVisible(true);
    }//GEN-LAST:event_MostrarProductActionPerformed

    private void MostrarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarProvActionPerformed
        // TODO add your handling code here:
        MostrarProv obj= new MostrarProv();
        obj.setVisible(true);
    }//GEN-LAST:event_MostrarProvActionPerformed

    private void EditarprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarprovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditarprovActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
                        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminNegocio().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConfigUsuario;
    private javax.swing.JMenuItem ConfigUsuario1;
    private javax.swing.JMenu Configuracion;
    private javax.swing.JMenuItem CorteCaja;
    private javax.swing.JMenuItem Editarprod;
    private javax.swing.JMenuItem Editarprov;
    private javax.swing.JMenuItem Editarvent;
    private javax.swing.JMenuItem EliminarProv;
    private javax.swing.JMenuItem Eliminarprod;
    private javax.swing.JMenuItem Ingresarpro;
    private javax.swing.JMenuItem Ingresarprov;
    private javax.swing.JMenu Inventario;
    private javax.swing.JMenuItem MostrarProduct;
    private javax.swing.JMenuItem MostrarProv;
    private javax.swing.JMenu Operaciones;
    private javax.swing.JMenu Proveedores;
    private javax.swing.JMenu Registrovent;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenu Ventas;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem impTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
conectar cc=new conectar();
Connection cn=cc.conexion();
}
