
package clases;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ProductList extends javax.swing.JFrame {
    String Catalog;
    public ProductList() {
        initComponents();
        mostrardatos("Vacio");
        this.setLocationRelativeTo(null);
        
    }
   
    private void isANumber(java.awt.event.KeyEvent evt){
      char keytyped = evt.getKeyChar();
      if (!((keytyped >= '0') && (keytyped <= '9') || keytyped==Character.MIN_VALUE) || (keytyped == '\u0000') || (keytyped == '\0') ) {
       //getToolkit().beep(); sonido de error de windows
        evt.consume();
      }
    }
    public void mostrardatos(String Valor){
        TbClientes.setDefaultRenderer(Object.class, new TablaImagen());
        DefaultTableModel modelo =new DefaultTableModel();
        modelo.addColumn("Clave Producto");
        modelo.addColumn("Descripción");
        modelo.addColumn("Categoría");
        modelo.addColumn("Existencias");
        modelo.addColumn("Precio de compra");
        modelo.addColumn("Precio de venta");
        modelo.addColumn("Ganancia");
        modelo.addColumn("Clave del proveedor");
        TbClientes.setModel(modelo);
        String sql="";
        if (Valor.equals("Vacio")) {
        sql="SELECT * FROM productos";    
        } else {
            if (CKName(Valor)) {
            sql="SELECT * FROM productos where IDP="+Valor+"";   
            }else{
            sql="SELECT * FROM productos WHERE Nompreproducto='" + Valor + "'"; 
            }
            
        }
        try{
        Object [] datos=new Object [8];
        Statement st= cn.createStatement();
        ResultSet rs=st.executeQuery(sql);    
            
            if (!rs.isBeforeFirst()) {
            JOptionPane.showMessageDialog(null, "No se encontro el producto con ese nombre o ID");   
            } else {
            while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);
            datos[4]=rs.getString(5);
            datos[5]=rs.getString(6);
            datos[6]=rs.getString(7);
            datos[7]=rs.getString(8);
            modelo.addRow(datos);
        TbClientes.setModel(modelo);
        TbClientes.setRowHeight(100);
            } }
        }catch (SQLException ex){
            Logger.getLogger(ProductList.class.getName()).log(Level.SEVERE,null,ex);
        }
    }

    public static boolean CKName(String Valor){
        for (char c : Valor.toCharArray()) {
            if (!Character.isDigit(c)) {
                return false;
            }
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Seleccionar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbClientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Clavepro = new javax.swing.JTextField();
        Descrproduc = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CantidadInv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PrecioUni = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Categ = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        PrecioVenta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Ganancia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CP = new javax.swing.JTextField();
        Buscar = new javax.swing.JTextField();
        Bus = new javax.swing.JButton();
        Mos = new javax.swing.JButton();

        Seleccionar.setText("Seleccionar");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Seleccionar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(189, 242, 224));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TbClientes.setBackground(new java.awt.Color(255, 204, 153));
        TbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TbClientes.setComponentPopupMenu(jPopupMenu1);
        TbClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 810, 290));
        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Inventario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Clave Provedor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Nombre del producto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        Clavepro.setEditable(false);
        Clavepro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(Clavepro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 160, -1));

        Descrproduc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(Descrproduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 160, -1));

        jButton2.setBackground(new java.awt.Color(25, 214, 210));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Añadir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        jButton3.setBackground(new java.awt.Color(25, 214, 210));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Clave del producto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        CantidadInv.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CantidadInv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantidadInvKeyTyped(evt);
            }
        });
        jPanel1.add(CantidadInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 160, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Categoría:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        PrecioUni.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(PrecioUni, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 160, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Existencias");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        Categ.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Categ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comida", "Hogar", "Electrónica", "Ropa", "Higiene" }));
        jPanel1.add(Categ, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Precio Compra");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        PrecioVenta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(PrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 160, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Precio Venta");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        Ganancia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(Ganancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 160, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Ganancia");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, 20));

        CP.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(CP, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 160, -1));

        Buscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 160, -1));

        Bus.setText("Buscar");
        Bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusActionPerformed(evt);
            }
        });
        jPanel1.add(Bus, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, -1, -1));

        Mos.setText("Mostrar todos los productos");
        Mos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MosActionPerformed(evt);
            }
        });
        jPanel1.add(Mos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
        // TODO add your handling code here:
        int fila=TbClientes.getSelectedRow();
        String category="";
        int op=0;
        if (fila>=0){           
            
            Clavepro.setText(TbClientes.getValueAt(fila,0).toString());
            Descrproduc.setText(TbClientes.getValueAt(fila,1).toString());
            PrecioUni.setText(TbClientes.getValueAt(fila,2).toString());
            CantidadInv.setText(TbClientes.getValueAt(fila,3).toString());
            category=TbClientes.getValueAt(fila,4).toString();
            switch (category){
                case "Comida":
                   op=0;
                   break;
                case "Hogar":
                   op=1;
                   break;
                case "Electrónica":
                   op=2;
                   break;
                case "Ropa":
                   op=3;
                   break;
                case"Higiene":
                   op=4;
                   break;
            }
            Categ.setSelectedIndex(op);
            Statement st;
        }else{
            JOptionPane.showMessageDialog(null, "No se seleccionó fila");
        }
    }//GEN-LAST:event_SeleccionarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int op=JOptionPane.showConfirmDialog(null, "¿Realmente desea abandonar \n esta página?", "Confirmar salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       
        if (op==0){
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try{
            boolean nuevo=true;
        String i="SELECT*FROM `productos` order by IDP desc limit 1;";
        int ID=0,categnum;
        String Category="";
        categnum=Categ.getSelectedIndex();
        switch (categnum){
            case 0:
            Category="Comida";
            break;
            case 1:
            Category="Hogar";
            break;
            case 2:
            Category="Electrónica";
            break;
            case 3:
            Category="Ropa";
            break;
            case 4:
            Category="Higiene";
            break;
                
        }
        com.mysql.jdbc.Statement st=(com.mysql.jdbc.Statement) cn.createStatement();
            ResultSet rs=st.executeQuery(i);
            
            while (rs.next()) {
            ID=Integer.parseInt(rs.getString(1))+1;}
            com.mysql.jdbc.Statement st2=(com.mysql.jdbc.Statement) cn.createStatement();
            com.mysql.jdbc.Statement st3=(com.mysql.jdbc.Statement) cn.createStatement();
            System.out.println("Entro 33");
            ResultSet rs2=st2.executeQuery("SELECT*FROM `productos`");
            System.out.println("Entro 4");
            while (rs2.next()) {
            //ResultSet rs3=st3.executeQuery("SELECT ");
                System.out.println(ID);
            String datos=rs2.getString(2);
                System.out.println(datos);
                if (datos.equals(Descrproduc.getText())) {
                    System.out.println("Es igual");
                    nuevo=false;
                    break;
                }
            }if(nuevo){
            PreparedStatement pst= cn.prepareStatement("INSERT INTO productos (IDP,Nompreproducto,Categoria,Existencias,Precio_compra,Precio_venta,Ganancia,Claveprov)values(?,?,?,?,?,?,?,?)"); 
            pst.setString(1, ID+"");
            pst.setString(2, Descrproduc.getText());
            pst.setString(3, Category);
            pst.setString(4, CantidadInv.getText());
            pst.setString(5, PrecioUni.getText());
            pst.setString(6, PrecioVenta.getText());
            pst.setString(7, Ganancia.getText());
            pst.setString(8, CP.getText());
            System.out.println("LLego");
            pst.executeUpdate();
            System.out.println("Paso");
            mostrardatos("");
        }else{
            JOptionPane.showMessageDialog(null, "Producto ya registrado con ID "+rs2.getString(1));}
        }
        
            catch(Exception e){
                System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CantidadInvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadInvKeyTyped

        isANumber(evt);
    }//GEN-LAST:event_CantidadInvKeyTyped

    private void TbClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbClientesMouseClicked
        // TODO add your handling code here:
        int fila= TbClientes.getSelectedRow();
        int op=0;
        String category="";
        if (fila>=0){
        Clavepro.setText(TbClientes.getValueAt(fila, 0).toString());
        Descrproduc.setText(TbClientes.getValueAt(fila,1).toString());
        switch (category){
            case "Comida":
                op=0;
                break;
            case "Hogar":
                op=1;
                break;
            case "Electrónica":
                op=2;
                break;
            case "Ropa":
                op=3;
                break;
            case "Higiene":
                op=4;
                break;
                
        }
        Categ.setSelectedIndex(op);
        CantidadInv.setText(TbClientes.getValueAt(fila, 3).toString());
        PrecioUni.setText(TbClientes.getValueAt(fila, 4).toString());
        PrecioVenta.setText(TbClientes.getValueAt(fila, 5).toString());
        Ganancia.setText(TbClientes.getValueAt(fila, 6).toString());
        CP.setText(TbClientes.getValueAt(fila, 7).toString());
        
        
        
        
        
        
        }else{
            JOptionPane.showMessageDialog(null, "No se seleccionó fila");
        }
    }//GEN-LAST:event_TbClientesMouseClicked

    private void BusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusActionPerformed
    mostrardatos(Buscar.getText()); 
    }//GEN-LAST:event_BusActionPerformed

    private void MosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MosActionPerformed
    mostrardatos("Vacio");
    }//GEN-LAST:event_MosActionPerformed
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bus;
    private javax.swing.JTextField Buscar;
    private javax.swing.JTextField CP;
    private javax.swing.JTextField CantidadInv;
    private javax.swing.JComboBox<String> Categ;
    private javax.swing.JTextField Clavepro;
    private javax.swing.JTextField Descrproduc;
    private javax.swing.JTextField Ganancia;
    private javax.swing.JButton Mos;
    private javax.swing.JTextField PrecioUni;
    private javax.swing.JTextField PrecioVenta;
    private javax.swing.JMenuItem Seleccionar;
    private javax.swing.JTable TbClientes;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
conectar cc=new conectar();
Connection cn=cc.conexion();
}
