package clases;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ProvList extends javax.swing.JFrame {

    public ProvList() {
        initComponents();
        mostrardatos();
        this.setLocationRelativeTo(null);
    }
public void limpiarpantalla(){
        LogoProv.setIcon(null);
        Rutaimg.setText("");
        Contactprov.setText("");
        Nombreprov.setText("");
        Claveprov.setText("");
    }
    public void mostrardatos(){
        TbClientes.setDefaultRenderer(Object.class, new TablaImagen());
        DefaultTableModel modelo =new DefaultTableModel();
        modelo.addColumn("CLAVE");
        modelo.addColumn("Proveedor");
        modelo.addColumn("No. Contacto");
        modelo.addColumn("RUTA");
        modelo.addColumn("LOGO");
        TbClientes.setModel(modelo);
        String sql="SELECT * FROM proveedores";
        try{
        Object [] datos=new Object [6];
        Statement st= cn.createStatement();
        ResultSet rs=st.executeQuery(sql);
        while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);
            Blob blob = rs.getBlob(5);
            try{
            byte []data = blob.getBytes(1, (int)blob.length());
            BufferedImage image = null; 
            InputStream in=new ByteArrayInputStream(data);
            image= ImageIO.read(in);
            ImageIcon imgi= new ImageIcon(image.getScaledInstance(100, 100, 0));
            datos[4]= new JLabel(imgi);
            }catch(Exception ex){
                datos[5]="No Imagen";
            }
            modelo.addRow(datos);
               
        }
        TbClientes.setModel(modelo);
        TbClientes.setRowHeight(100);
        }catch (SQLException ex){
            Logger.getLogger(ProvList.class.getName()).log(Level.SEVERE,null,ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Seleccionar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbClientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Rutaimg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Claveprov = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        LogoProv = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Nombreprov = new javax.swing.JTextField();
        Rutaarch = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Contactprov = new javax.swing.JTextField();
        limp = new javax.swing.JButton();

        Seleccionar.setText("Seleccionar");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Seleccionar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(189, 242, 224));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TbClientes.setBackground(new java.awt.Color(172, 255, 255));
        TbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TbClientes.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(TbClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 470, 290));
        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Lista de proveedores");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Número de contacto:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        Rutaimg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(Rutaimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 100, 40));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Nombre del proveedor:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        Claveprov.setEditable(false);
        Claveprov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(Claveprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 160, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Ruta:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        LogoProv.setBackground(new java.awt.Color(172, 255, 255));
        LogoProv.setOpaque(true);
        jPanel1.add(LogoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 100, 100));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Logo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        Nombreprov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(Nombreprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 140, -1));

        Rutaarch.setBackground(new java.awt.Color(25, 214, 210));
        Rutaarch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Rutaarch.setForeground(new java.awt.Color(255, 255, 255));
        Rutaarch.setText("Seleccionar foto");
        Rutaarch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Rutaarch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutaarchActionPerformed(evt);
            }
        });
        jPanel1.add(Rutaarch, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 150, 40));

        jButton1.setBackground(new java.awt.Color(25, 214, 210));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        jButton2.setBackground(new java.awt.Color(25, 214, 210));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Añadir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        jButton3.setBackground(new java.awt.Color(25, 214, 210));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, -1, -1));

        jButton4.setBackground(new java.awt.Color(25, 214, 210));
        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Borrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Clave del proveedor:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        Contactprov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(Contactprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 160, -1));

        limp.setBackground(new java.awt.Color(25, 214, 210));
        limp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        limp.setForeground(new java.awt.Color(255, 255, 255));
        limp.setText("Limpiar");
        limp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpActionPerformed(evt);
            }
        });
        jPanel1.add(limp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RutaarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutaarchActionPerformed
        // TODO add your handling code here:
        JFileChooser archivo= new JFileChooser();
        int ventana= archivo.showOpenDialog(null);
        if (ventana== JFileChooser.APPROVE_OPTION){
            File file=archivo.getSelectedFile();
            Rutaimg.setText(String.valueOf(file));
            Image foto=getToolkit().getImage(Rutaimg.getText());
            foto=foto.getScaledInstance(100, 100, Image.SCALE_DEFAULT);
            LogoProv.setIcon(new ImageIcon(foto));
        }
    }//GEN-LAST:event_RutaarchActionPerformed

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
        // TODO add your handling code here:
        int fila=TbClientes.getSelectedRow();
        if (fila>=0){           
            Claveprov.setText(TbClientes.getValueAt(fila,0).toString());
            Nombreprov.setText(TbClientes.getValueAt(fila,1).toString());
            Contactprov.setText(TbClientes.getValueAt(fila,2).toString());
            Rutaimg.setText(TbClientes.getValueAt(fila,3).toString());
            Statement st;
            try {
                st = cn.createStatement();
                ResultSet rs=st.executeQuery("SELECT * FROM proveedores WHERE ClaveProv='"+Claveprov.getText()+"'");
                try{
                BufferedImage image=null;
                if (rs.next()) {
                    com.mysql.jdbc.Blob bytesImagen = (com.mysql.jdbc.Blob) rs.getBlob(5);
                    byte[] data = bytesImagen.getBytes(1, (int) bytesImagen.length());
                    InputStream in= new ByteArrayInputStream(data);
                    image= ImageIO.read(in);
                    ImageIcon imgi=new ImageIcon(image.getScaledInstance(100, 100, 0));
                    LogoProv.setIcon(imgi);
                }
                }catch(Exception ex){
                        
                        }
                    
                
            } catch (SQLException ex) {
                Logger.getLogger(ProductList.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "No se seleccionó fila");
        }
    }//GEN-LAST:event_SeleccionarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int op=JOptionPane.showConfirmDialog(null, "¿Realmente desea borrar este proveedor?", "Confirmar borrar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       
        if (op==0){
        try{
            PreparedStatement pst=cn.prepareStatement("DELETE FROM proveedores WHERE ClaveProv ='"+Claveprov.getText()+"'");
            pst.executeUpdate();
            mostrardatos ();
            limpiarpantalla();
        }catch(Exception e){
            
        }}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            
            FileInputStream archivofoto;
            PreparedStatement pst= (PreparedStatement)cn.prepareStatement("UPDATE proveedores SET ClaveProv= ?,Nombrecomp= ?, Contacto=?, Ruta=?, Logo=? WHERE ClaveProv='"+Claveprov.getText()+"'");
        pst.setString(1, Claveprov.getText());
        pst.setString(2, Nombreprov.getText());
        pst.setString(3, Contactprov.getText());
        pst.setString(4, Rutaimg.getText());
        archivofoto = new FileInputStream (Rutaimg.getText());
        pst.setBinaryStream(5, archivofoto);
        pst.executeUpdate();
        mostrardatos();
        limpiarpantalla();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int op=JOptionPane.showConfirmDialog(null, "¿Realmente desea abandonar \n esta página?", "Confirmar salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       
        if (op==0){
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            boolean nuevo=true;
        String i="SELECT*FROM `proveedores` order by ClaveProv desc limit 1;";
        int ID=0;
        com.mysql.jdbc.Statement st=(com.mysql.jdbc.Statement) cn.createStatement();
            ResultSet rs=st.executeQuery(i);
            while (rs.next()) {
            ID=Integer.parseInt(rs.getString(1))+1;}
            com.mysql.jdbc.Statement st2=(com.mysql.jdbc.Statement) cn.createStatement();
            ResultSet rs2=st2.executeQuery("SELECT*FROM `proveedores`");
            while (rs2.next()) {
            String datos=rs2.getString(2);
                if (datos.equals(Nombreprov.getText())) {
                    nuevo=false;
                    break;
                }
            }
            if(nuevo){
            FileInputStream archivofoto;
            PreparedStatement pst= cn.prepareStatement("INSERT INTO proveedores (ClaveProv,Nombrecomp,Contacto,Ruta,Logo)values(?,?,?,?,?)");
            pst.setString(1, ID+"");
            pst.setString(2, Nombreprov.getText());
            pst.setString(3, Contactprov.getText());
            pst.setString(4, Rutaimg.getText());
            archivofoto = new FileInputStream(Rutaimg.getText());
            pst.setBinaryStream(5, archivofoto);
            pst.executeUpdate();
            mostrardatos();
            limpiarpantalla();}
            else{
                JOptionPane.showMessageDialog(null, "Proveedor ya registrado anteriormente");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Imagen muy pesada para el sistema");
             
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void limpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpActionPerformed
        // TODO add your handling code here:
        limpiarpantalla();
    }//GEN-LAST:event_limpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProvList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProvList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProvList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProvList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProvList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Claveprov;
    private javax.swing.JTextField Contactprov;
    private javax.swing.JLabel LogoProv;
    private javax.swing.JTextField Nombreprov;
    private javax.swing.JButton Rutaarch;
    private javax.swing.JTextField Rutaimg;
    private javax.swing.JMenuItem Seleccionar;
    private javax.swing.JTable TbClientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limp;
    // End of variables declaration//GEN-END:variables
conectar cc=new conectar();
Connection cn=cc.conexion();
}
