/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clases;

import static clases.ProductList.CKName;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felip
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
        mostrardatos("");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbClientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Clavepro = new javax.swing.JTextField();
        Descrproduc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CantidadInv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PrecioUni = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Categ = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        PrecioVenta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Ganancia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CP = new javax.swing.JTextField();
        Buscar = new javax.swing.JTextField();
        Bus = new javax.swing.JButton();
        Mos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(189, 242, 224));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TbClientes.setBackground(new java.awt.Color(255, 204, 153));
        TbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TbClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 810, 290));
        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Inventario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Clave Provedor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Nombre del producto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        Clavepro.setEditable(false);
        Clavepro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(Clavepro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 160, -1));

        Descrproduc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(Descrproduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 160, -1));

        jButton1.setBackground(new java.awt.Color(25, 214, 210));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, -1));

        jButton3.setBackground(new java.awt.Color(25, 214, 210));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Clave del producto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        CantidadInv.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CantidadInv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantidadInvKeyTyped(evt);
            }
        });
        jPanel1.add(CantidadInv, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 160, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Categoría:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        PrecioUni.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(PrecioUni, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 160, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Existencias");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        Categ.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Categ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comida", "Hogar", "Electrónica", "Ropa", "Higiene" }));
        jPanel1.add(Categ, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Precio Compra");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        PrecioVenta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(PrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 160, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Precio Venta");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        Ganancia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(Ganancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 160, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Ganancia");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, 20));

        CP.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(CP, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 160, -1));

        Buscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 160, -1));

        Bus.setText("Buscar");
        Bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusActionPerformed(evt);
            }
        });
        jPanel1.add(Bus, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, -1, -1));

        Mos.setText("Mostrar todos los productos");
        Mos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MosActionPerformed(evt);
            }
        });
        jPanel1.add(Mos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 902, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try{
            PreparedStatement pst= (PreparedStatement)cn.prepareStatement("UPDATE productos SET IDP= ?,Nompreproducto= ?, Categoria=?, Existencias=?,Precio_compra=? ,Precio_venta=?, Ganancia=?, Claveprov=? WHERE IDP='"+Clavepro.getText()+"'");
            int ID=0,categnum;
            String Category="";
            categnum=Categ.getSelectedIndex();
            switch (categnum){
                case 0:
                Category="Comida";
                break;
                case 1:
                Category="Hogar";
                break;
                case 2:
                Category="Electrónica";
                break;
                case 3:
                Category="Ropa";
                break;
                case 4:
                Category="Higiene";
                break;

            }
            pst.setString(1, Clavepro.getText());
            pst.setString(2, Descrproduc.getText());
            pst.setString(3, Category);
            System.out.println(Category);
            pst.setString(4, CantidadInv.getText());
            pst.setString(5, PrecioUni.getText());
            pst.setString(6, PrecioVenta.getText());
            pst.setString(7, Ganancia.getText());
            pst.setString(8, CP.getText());
            pst.executeUpdate();
            mostrardatos("");

        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int op=JOptionPane.showConfirmDialog(null, "¿Realmente desea abandonar \n esta página?", "Confirmar salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (op==0){
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CantidadInvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadInvKeyTyped
        
    }//GEN-LAST:event_CantidadInvKeyTyped

    private void TbClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbClientesMouseClicked
       int fila= TbClientes.getSelectedRow();
        int op=0;
        String category="";
        if (fila>=0){
        Clavepro.setText(TbClientes.getValueAt(fila, 0).toString());
        Descrproduc.setText(TbClientes.getValueAt(fila,1).toString());
        switch (category){
            case "Comida":
                op=0;
                break;
            case "Hogar":
                op=1;
                break;
            case "Electrónica":
                op=2;
                break;
            case "Ropa":
                op=3;
                break;
            case "Higiene":
                op=4;
                break;
                
        }
        Categ.setSelectedIndex(op);
        CantidadInv.setText(TbClientes.getValueAt(fila, 3).toString());
        PrecioUni.setText(TbClientes.getValueAt(fila, 4).toString());
        PrecioVenta.setText(TbClientes.getValueAt(fila, 5).toString());
        Ganancia.setText(TbClientes.getValueAt(fila, 6).toString());
        CP.setText(TbClientes.getValueAt(fila, 7).toString());
        
        
        
        
        
        
        }else{
            JOptionPane.showMessageDialog(null, "No se seleccionó fila");
        }
    }//GEN-LAST:event_TbClientesMouseClicked

    private void BusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusActionPerformed
        mostrardatos(Buscar.getText());
    }//GEN-LAST:event_BusActionPerformed

    private void MosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MosActionPerformed
        mostrardatos("");
    }//GEN-LAST:event_MosActionPerformed

    
    public void mostrardatos(String Valor){
        TbClientes.setDefaultRenderer(Object.class, new TablaImagen());
        DefaultTableModel modelo =new DefaultTableModel();
        modelo.addColumn("Clave Producto");
        modelo.addColumn("Descripción");
        modelo.addColumn("Categoría");
        modelo.addColumn("Existencias");
        modelo.addColumn("Precio de compra");
        modelo.addColumn("Precio de venta");
        modelo.addColumn("Ganancia");
        modelo.addColumn("Clave del proveedor");
        TbClientes.setModel(modelo);
        String sql="";
        if (Valor.equals("")) {
        sql="SELECT * FROM productos";    
        } else {
            if (CKName(Valor)) {
            sql="SELECT * FROM productos where IDP="+Valor+"";    
            }else if(!CKName(Valor)){
            sql="SELECT * FROM productos where Nompreproducto="+Valor+"";    
            }else{
             JOptionPane.showMessageDialog(null, "Articulo no encontrado");         
                    }
            
        }
        try{
        Object [] datos=new Object [8];
        Statement st= cn.createStatement();
        ResultSet rs=st.executeQuery(sql);
        while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);
            datos[4]=rs.getString(5);
            datos[5]=rs.getString(6);
            datos[6]=rs.getString(7);
            datos[7]=rs.getString(8);
            modelo.addRow(datos);
        }
        TbClientes.setModel(modelo);
        TbClientes.setRowHeight(100);
        }catch (SQLException ex){
            Logger.getLogger(ProductList.class.getName()).log(Level.SEVERE,null,ex);
        }
    }

    public static boolean CKName(String Valor){
        for (char c : Valor.toCharArray()) {
            if (!Character.isDigit(c)) {
                return false;
            }
        }
        return true;
    }
    conectar cc=new conectar();
Connection cn=cc.conexion();
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bus;
    private javax.swing.JTextField Buscar;
    private javax.swing.JTextField CP;
    private javax.swing.JTextField CantidadInv;
    private javax.swing.JComboBox<String> Categ;
    private javax.swing.JTextField Clavepro;
    private javax.swing.JTextField Descrproduc;
    private javax.swing.JTextField Ganancia;
    private javax.swing.JButton Mos;
    private javax.swing.JTextField PrecioUni;
    private javax.swing.JTextField PrecioVenta;
    private javax.swing.JTable TbClientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
