/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clases;

import com.mysql.jdbc.Connection;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shand
 */
public class Ventas extends javax.swing.JFrame {

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
        mostrardatos("","");
        this.setLocationRelativeTo(null);
    }
    public void limpiarpantalla(){
        NombreClient.setText("");
        ShowClientID.setText("");
        Claveproduct.setText("");
        Cantprod.setText("");
        Categ.setSelectedIndex(0);
    }
    public void IDvend(String ID){
        ClaveUser.setText(ID);
    }
        public void mostrardatos(String categ,String nom){
        TbClientes.setDefaultRenderer(Object.class, new TablaImagen());
        DefaultTableModel modelo =new DefaultTableModel();
        modelo.addColumn("Clave Producto");
        modelo.addColumn("Descripción");
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Categoria");
        modelo.addColumn("Imagen");
        TbClientes.setModel(modelo);
        String sql="";
        if (categ.equals("")){
            sql="SELECT * FROM productos";
            
        }else{
            sql="SELECT * FROM productos WHERE Categ= '"+categ+"'";
        }
        if (!nom.equals("")){
            sql="SELECT * FROM productos WHERE Codpro= '"+nom+"'";
        } else {
        }
        try{
        Object [] datos=new Object [8];
        Statement st= cn.createStatement();
        ResultSet rs=st.executeQuery(sql);
        while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);
            datos[4]=rs.getString(5);
            Blob blob = rs.getBlob(7);
            try{
            byte []data = blob.getBytes(1, (int)blob.length());
            BufferedImage image = null; 
            InputStream in=new ByteArrayInputStream(data);
            image= ImageIO.read(in);
            ImageIcon imgi= new ImageIcon(image.getScaledInstance(100, 100, 0));
            datos[5]= new JLabel(imgi);
            }catch(Exception ex){
                datos[7]="No Imagen";
            }
            modelo.addRow(datos);
        }
        TbClientes.setModel(modelo);
        TbClientes.setRowHeight(100);
        }catch (SQLException ex){
            Logger.getLogger(ProductList.class.getName()).log(Level.SEVERE,null,ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        Addtokart = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbClientes = new javax.swing.JTable();
        Categ = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Claveproduct = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ClaveUser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NombreClient = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ShowClientID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Cantprod = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Buscpro = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Addtokart.setBackground(new java.awt.Color(189, 242, 224));
        Addtokart.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Addtokart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        Addtokart.setText("Agregar al carrito");
        Addtokart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddtokartActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Addtokart);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(189, 242, 224));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TbClientes.setBackground(new java.awt.Color(255, 204, 153));
        TbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TbClientes.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(TbClientes);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 490, 260));

        Categ.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Categ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todo", "Comida", "Hogar", "Electrónica", "Ropa", "Higiene" }));
        Categ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategActionPerformed(evt);
            }
        });
        jPanel2.add(Categ, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Clave del Producto:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Clave del vendedor:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
        jPanel2.add(Claveproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 170, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Clave del cliente:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        ClaveUser.setEditable(false);
        ClaveUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel2.add(ClaveUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 140, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Cantidad:");
        jLabel8.setToolTipText("");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jButton1.setBackground(new java.awt.Color(25, 214, 210));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Busqueda.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        NombreClient.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel2.add(NombreClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 170, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Realizar venta");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 180, 40));

        ShowClientID.setEditable(false);
        ShowClientID.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel2.add(ShowClientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 140, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Categoría:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Nombre del cliente:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        Cantprod.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Cantprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CantprodKeyTyped(evt);
            }
        });
        jPanel2.add(Cantprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 160, -1));

        jButton2.setBackground(new java.awt.Color(25, 214, 210));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrito-de-compras.png"))); // NOI18N
        jButton2.setText("Ver carrito");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, 30));

        jButton3.setBackground(new java.awt.Color(25, 214, 210));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, -1, 30));

        Buscpro.setBackground(new java.awt.Color(25, 214, 210));
        Buscpro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Buscpro.setForeground(new java.awt.Color(255, 255, 255));
        Buscpro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Busqueda.png"))); // NOI18N
        Buscpro.setText("Buscar");
        Buscpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscproActionPerformed(evt);
            }
        });
        jPanel2.add(Buscpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        jButton4.setBackground(new java.awt.Color(25, 214, 210));
        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escoba.png"))); // NOI18N
        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql="SELECT * FROM clientes";
        String [] data=new String [2];
        int a=0;
        try{
            Statement st= cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
            data[0]=rs.getString(1);
            if (data[0].equals(NombreClient.getText())){
                data[1]=rs.getString(3);
                ShowClientID.setText(data[1]);
                a=1;
            }
            }
            if (a==0){
                JOptionPane.showMessageDialog(null,"No existe un cliente con ese nombre");
            }
        }catch (SQLException ex){
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BuscproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscproActionPerformed
        // TODO add your handling code here:
        String sql="SELECT * FROM productos WHERE Codpro= '"+Claveproduct.getText()+"'";
        String [] data=new String [2];
        int a=0;
        try{
            Statement st= cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
            data[0]=rs.getString(1);
            if (data[0].equals(Claveproduct.getText())){
                mostrardatos("",Claveproduct.getText());
                a=1;
            }
            }
            if (a==0){
                JOptionPane.showMessageDialog(null,"No existe un producto con esa clave");
            }
        }catch (SQLException ex){
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE,null,ex);
        }
        
    }//GEN-LAST:event_BuscproActionPerformed
    private void isANumber(java.awt.event.KeyEvent evt){
      char keytyped = evt.getKeyChar();
      if (!((keytyped >= '0') && (keytyped <= '9') || keytyped==Character.MIN_VALUE) || (keytyped == '\u0000') || (keytyped == '\0') ) {
       //getToolkit().beep(); sonido de error de windows
        evt.consume();
      }
    }
    private void CantprodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantprodKeyTyped
        // TODO add your handling code here:
        isANumber(evt);       
    }//GEN-LAST:event_CantprodKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int op=JOptionPane.showConfirmDialog(null, "¿Realmente desea abandonar \n esta página?", "Confirmar salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       
        if (op==0){
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void AddtokartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddtokartActionPerformed
        int fila=TbClientes.getSelectedRow();
        boolean nuevo=true;
        if (fila>=0){
        String codpro=TbClientes.getValueAt(fila,0).toString();
        String precio=TbClientes.getValueAt(fila,2).toString();
        String stocktotal=TbClientes.getValueAt(fila,3).toString();
        int Stockprod=Integer.parseInt(stocktotal);
        if(!ShowClientID.getText().equals("")){
           if(!Cantprod.getText().equals("")){
               int Stockcomp=Integer.parseInt(Cantprod.getText());
               if(Stockcomp!=0){
                   if(Stockcomp<=Stockprod){
                       try{
                           com.mysql.jdbc.Statement st2=(com.mysql.jdbc.Statement) cn.createStatement();
                           ResultSet rs2=st2.executeQuery("SELECT*FROM `ventas`");
                           while (rs2.next()) {
                           String data=rs2.getString(3);
                               if(codpro.equals(data)){
                                   nuevo=false;
                                   break;
                               }   
                           }
                           if (nuevo) {
                           java.sql.PreparedStatement pst= cn.prepareStatement("INSERT INTO ventas (IDUser,ClaveCli,ClavePro,Cantidad,Precio)values(?,?,?,?,?)");
                           pst.setString(1, ClaveUser.getText());
                           pst.setString(2, ShowClientID.getText());
                           pst.setString(3, codpro);
                           pst.setString(4, Cantprod.getText());
                           double precitotal,preciuni,canti;
                           canti=Double.parseDouble(Cantprod.getText());
                           preciuni=Double.parseDouble(precio);
                           precitotal=canti*preciuni;
                           pst.setString(5,Double.toString(precitotal));
                           pst.executeUpdate();
                           mostrardatos("","");
                           Claveproduct.setText("");
                           Cantprod.setText("");
                           }else{
                            JOptionPane.showMessageDialog(null, "No se pueden añadir dos veces el mismo productos");
                           }
                       }catch(Exception e){
                           System.out.println(e);
                       }
                   }else{
                    JOptionPane.showMessageDialog(null, "Ingrese una cantidad menor \n al inventario total");  
                   }
               }else{
                   Cantprod.setText("Cantidad inválida");
               }
           }else{
               Cantprod.setText("Ingrese la cantidad a comprar");
           }
        }else{
            NombreClient.setText("Ingrese un cliente");
        }
        }else{
            JOptionPane.showMessageDialog(null, "No se seleccionó fila");
        }

        
    }//GEN-LAST:event_AddtokartActionPerformed

    private void CategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategActionPerformed
        // TODO add your handling code here:
        int ID=0,categnum=Categ.getSelectedIndex();
        String Category="";
        
        switch (categnum){
            case 0:
            Category="";
            break;
            case 1:
            Category="Comida";
            break;
            case 2:
            Category="Hogar";
            break;
            case 3:
            Category="Electrónica";
            break;
            case 4:
            Category="Ropa";
            break;
            case 5:
            Category="Higiene";
        }
        mostrardatos(Category,"");
    }//GEN-LAST:event_CategActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        limpiarpantalla();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Carrito obj= new Carrito();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Addtokart;
    private javax.swing.JButton Buscpro;
    private javax.swing.JTextField Cantprod;
    private javax.swing.JComboBox<String> Categ;
    private javax.swing.JTextField ClaveUser;
    private javax.swing.JTextField Claveproduct;
    private javax.swing.JTextField NombreClient;
    private javax.swing.JTextField ShowClientID;
    private javax.swing.JTable TbClientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
conectar cc=new conectar();
Connection cn=(Connection) cc.conexion();
}
